stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_USER/vue3-admin:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $SERVER_USER@$SERVER_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_HOST "docker pull $DOCKER_IMAGE"
    - ssh $SERVER_USER@$SERVER_HOST "docker stop vue3-admin || true"
    - ssh $SERVER_USER@$SERVER_HOST "docker rm vue3-admin || true"
    - ssh $SERVER_USER@$SERVER_HOST "docker run -d --name vue3-admin -p 80:80 $DOCKER_IMAGE"
  only:
    - main 