name: Deploy to Production

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    # 添加一个超时设置，避免任务无限期排队
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t 13jden/travel-admin-fronted:latest .
      
      - name: Deploy to server
        run: |
          docker stop vue3-admin || true
          docker rm vue3-admin || true
          docker run -d --name vue3-admin -p 3000:80 13jden/travel-admin-fronted:latest 